name: dokdonia
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python >= 3.9
  - pip
  - r-base
  - tzlocal
  - pip:
    - numpy
    - matplotlib
    - biopython
    - rpy2
    - scikit-learn
    - pandas
    - clust
    - ipykernel
    - poetry